version: "3.6"

services:
  reverse-proxy:
    image: votingapp-proxy 
    build:
      context: ./nginx
    ports:
      - 8080:80

  votingapp:
    image: ${REGISTRY:-paulopez}/votingapp:${TAG:-latest}
    build:
      context: ./src/votingapp
      dockerfile: Dockerfile
    environment: 
      REDIS: database:6379

  database:
    image: redis
  
  votingapp-test:
    image: votingapp-test
    build:
      context: ./test
    environment: 
      VOTING_URL: http://votingapp/vote
